name: Sync with Stainless
on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync OpenAPI spec
    steps:
      - uses: actions/checkout@v3
      - uses: stainless-api/upload-openapi-spec-action@main
        with:
          stainless_api_key: ${{ secrets.STAINLESS_API_KEY }}
          input_path: "openapi.yaml"
          project_name: "raccoonai"
